-- Phase 2 secure Space access domain foundation.
-- UUIDs are generated by the application so IDs remain portable across storage boundaries.

CREATE TYPE space_state AS ENUM ('active', 'archived', 'deleting', 'deleted');
CREATE TYPE membership_state AS ENUM ('active', 'left', 'removed');
CREATE TYPE membership_role AS ENUM ('owner', 'member', 'guest');
CREATE TYPE invitation_state AS ENUM ('active', 'revoked', 'exhausted');

CREATE TABLE spaces (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 120),
    state space_state NOT NULL DEFAULT 'active',
    created_by_identity_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    archived_at TIMESTAMPTZ,
    deleting_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CHECK (
        (state = 'active' AND archived_at IS NULL AND deleting_at IS NULL AND deleted_at IS NULL)
        OR (state = 'archived' AND archived_at IS NOT NULL AND deleting_at IS NULL AND deleted_at IS NULL)
        OR (state = 'deleting' AND archived_at IS NOT NULL AND deleting_at IS NOT NULL AND deleted_at IS NULL)
        OR (state = 'deleted' AND archived_at IS NOT NULL AND deleting_at IS NOT NULL AND deleted_at IS NOT NULL)
    )
);

CREATE TABLE memberships (
    id UUID PRIMARY KEY,
    space_id UUID NOT NULL REFERENCES spaces(id),
    identity_id UUID NOT NULL,
    role membership_role NOT NULL,
    state membership_state NOT NULL DEFAULT 'active',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    CHECK (
        (state = 'active' AND ended_at IS NULL)
        OR (state IN ('left', 'removed') AND ended_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX memberships_one_active_identity_per_space
    ON memberships (space_id, identity_id)
    WHERE state = 'active';

CREATE UNIQUE INDEX memberships_one_active_owner_per_space
    ON memberships (space_id)
    WHERE state = 'active' AND role = 'owner';

CREATE UNIQUE INDEX memberships_space_and_id_unique
    ON memberships (space_id, id);

CREATE TABLE invitations (
    id UUID PRIMARY KEY,
    space_id UUID NOT NULL REFERENCES spaces(id),
    created_by_membership_id UUID NOT NULL,
    secret_hash BYTEA NOT NULL UNIQUE CHECK (octet_length(secret_hash) >= 32),
    state invitation_state NOT NULL DEFAULT 'active',
    expires_at TIMESTAMPTZ NOT NULL,
    max_uses INTEGER CHECK (max_uses IS NULL OR max_uses > 0),
    use_count INTEGER NOT NULL DEFAULT 0 CHECK (use_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ,
    CHECK (expires_at > created_at),
    CHECK (max_uses IS NULL OR use_count <= max_uses),
    CHECK (
        (state = 'revoked' AND revoked_at IS NOT NULL)
        OR (state <> 'revoked' AND revoked_at IS NULL)
    ),
    FOREIGN KEY (space_id, created_by_membership_id)
        REFERENCES memberships (space_id, id)
);

CREATE INDEX memberships_identity_active_idx
    ON memberships (identity_id, space_id)
    WHERE state = 'active';

CREATE INDEX invitations_active_space_idx
    ON invitations (space_id, expires_at)
    WHERE state = 'active';
